name: "Assert Branch Naming Convention"
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+(:\s)([a-z])+' # Regex the title should match.
          allowed_prefixes: "feat,fix,chore, ci" # title should start with the given prefix
          # disallowed_prefixes: "feat/,hotfix" # title should not start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
