name: "CI"
on: pull_request
jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+(:\s)([a-z])+' # Regex the title should match.
          allowed_prefixes: "feat,fix,chore, ci" # title should start with the given prefix
          # disallowed_prefixes: "feat/,hotfix" # title should not start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 35 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.EMAIL_ACCOUNT}}
          # Optional (recommended) mail server password:
          password: ${{secrets.EMAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: fernando.montero.perez@gmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
